# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-24 10:59
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heaven', '0004_auto_20161224_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cemetery',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=8, validators=[django.core.validators.MinValueValidator(-85.05115), django.core.validators.MaxValueValidator(85.05115)]),
        ),
        migrations.AlterField(
            model_name='cemetery',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
